### ISSUE TITLE
Fade doesn't apply to cached (?) chunks

### ISSUE THREAD

**Issue by sisby-folk** [kerudion/chunksfadein#1] opened 2022-12-05 02:29 UTC
Hey there! Really enjoying the mod so far, we've been looking for a modern chunk fade mod for ages! ^^

I think I've found an issue with the way the mod interacts with chunks that have only recently been unloaded (I'm assuming they're cached)

It seems like the fadeCoeff is already 1 for these chunks, and there's nothing setting it back to 0 when they stop being rendered - so they appear without fading.

Here's a video of me (zoomed in) backtracking over chunks I just visited.

https://user-images.githubusercontent.com/55819817/205535582-df2a4ae2-7e12-4e12-99bf-e9064c62f0a3.mp4

If my assumptions here are right, it sounds like there just needs to be some way to reset the fadeCoeff when the chunk stops being rendered.

If you can't reproduce anything, let me know and I'll bisect for incompatibilities.

**Comment by kerudion** [comment] 2022-12-05 07:09
Hi! Probably that's because that RenderRegion wasn't fully unloaded, so my mod haven't reset fadeCoeff for chunks which was in that RenderRegion. I think I can fix this by injecting reset logic to RenderRegion.removeChunk() method

**Comment by sisby-folk** [comment] 2022-12-06 06:21
Seems to be partially fixed, but still possible to reproduce chunks appearing without fadein in some cases

(nb: after the delta-t changes, the mod is working really well, definitely tossing it in our next modpack update)

https://user-images.githubusercontent.com/55819817/205836625-6855b613-c964-46f3-a2a8-1c72f731ee2e.mp4

**Comment by kerudion** [comment] 2022-12-06 19:38
That's very strange, I'll try do debug more to find the source of issue

**Comment by kerudion** [comment] 2022-12-08 11:51
Fade doesn't reset these chunks, because they aren't removed, only not rendered. I tried resetting non-rendered chunks, but this also resets fade for chunks behind you. I can't fix it now :(

**Comment by sisby-folk** [comment] 2022-12-08 12:17
hmm, I assume it'd be too hacky of a workaround to check the clients position and render distance relative to the chunk when it starts being rendered again?

Beyond that, I guess you'd need something exposed within sodium itself to know whether something is being rendered again due to camera movement or player movement - if that code is separate enough, you might be able to mix in to it, but I'm not sure.

**Comment by kerudion** [comment] 2022-12-08 12:58
Yeah, maybe I can find that piece of code that decides what chunks to render and mixin into it if possible. If it's not possible to mixin into it, probably I can copy that code and perform these checks myself.
But today I'll try to implement chunk animations and work on this issue afterwards.

**Comment by theRookieCoder** [comment] 2023-01-21 09:17
This also an issue with Distant Horizons, but that would be difficult to be compatible with since (I think) it uses a custom renderer.

**Comment by RaptaG** [comment] 2023-02-04 20:14
I can reproduce this issue, both with cached chunks and Distant Horizons chunks.

**Comment by RaptaG** [comment] 2023-03-03 18:53
Have you made any progress with this @kerudion?

**Comment by kerudion** [comment] 2023-03-03 19:38
Not really, now I'm just looking at Sodium and Minecraft code and trying to find something useful for that issue

**Comment by kerudion** [comment] 2023-08-15 11:03
I've changed how fade values are stored in new 1.20.1 version and this issue disappeared. Also I'll port these changes to 1.20, 1.19.x and 1.18.x versions, so I hope that it'll be fixed once and for all.

**Closed by kerudion** 2023-08-15 11:03 UTC
Labels: bug, good first issue
