### ISSUE TITLE
Crash on Launch Attempt

### ISSUE THREAD

**Issue by Obscure2020** [kerudion/chunksfadein#14] opened 2022-12-26 23:48 UTC
I tried updating to v2.0.0-1.19.3.\
Unfortunately, I ran into a crash that prevented the game from completing the load process. The game window actually did open for a few seconds, but remained pure white, and then crashed again immediately after.

The bug disappeared upon reverting to v1.0.0-1.19.3.

[Here is a link](https://paste.atlauncher.com/view/42b80363-260d-4c44-9b4d-092590589273) to the crash log. If you would like me to provide the full list of mods I'm using separately, let me know.

**Comment by kerudion** [comment] 2022-12-27 09:54
Essentially, a duplicate of #13

**Closed by kerudion** 2022-12-27 09:54 UTC
