### ISSUE TITLE
Crash When Dimension Hopping with Shaders Enabled

### ISSUE THREAD

**Issue by Fourbo** [kerudion/chunksfadein#17] opened 2022-12-28 12:27 UTC
**Description:** When I was last playing, after I created a portal and traveled to the Nether, the game crashed. After testing it again, and going to the Nether, the game loads fine, but as soon as I pressed k to enable shaders, the game crashed. There seems to be some conflict with Iris and this mod based on the crash log causing the error.

**Crash Report**
[crash-2022-12-28_04.12.52-client.txt](https://github.com/kerudion/chunksfadein/files/10314199/crash-2022-12-28_04.12.52-client.txt)
**Latest Log**
[latest.log](https://github.com/kerudion/chunksfadein/files/10314201/latest.log)

**Comment by kerudion** [comment] 2022-12-28 14:02
Seems like a shader-specific issue, I can't reproduce it myself. Can you try to run the game without chunksfadein, and see what happens?

**Comment by kerudion** [comment] 2022-12-28 14:50
I've found source of the error, I'll try to fix it now

**Comment by kerudion** [comment] 2022-12-28 17:51
Fixed in [48db7be](https://github.com/kerudion/chunksfadein/commit/48db7be837dd248b788486779c8bdc71c7bb3326)

**Closed by kerudion** 2022-12-28 17:51 UTC
Labels: bug
