### ISSUE TITLE
[BUG]: Skinshuffle incompatibility

### ISSUE THREAD

**Issue by maevius669** [kerudion/chunksfadein#82] opened 2024-07-02 17:13 UTC
### Before creating an issue, please make sure you have checked the following:

- [X] This issue does not appear without Chunks Fade In installed.
- [X] All my mods (not only Chunks Fade In) are up-to-date.
- [X] Similar issue had not already been reported before in the [issue tracker](https://github.com/kerudion/chunksfadein/issues).

### What happened?

game crashes when skinshuffle is installed.
i include a 1.20.1 version though im not sure if you want to fix that version

### Steps to reproduce

1.21: launch game.
 
in 1.20.1 logs, it crashes when exiting world but crashes will happen when launching, if emf/etf is installed

### Logs

1.21 https://mclo.gs/dCzV87w
1.20.1 https://mclo.gs/PbCg5f6

**Comment by Felix14-v2** [comment] 2024-07-03 13:44
Are you sure the crash is caused by ChunkFadeIn, and it doesn't appear without Chunks Fade In installed?

**Comment by Felix14-v2** [comment] 2024-07-03 13:46
Oh, exactly, SkinShuffle creates a dummy world to render a player model (even in title screen), and CFI can't handle it.

**Comment by IMB11** [comment] 2024-07-07 16:44
Please let me know what I can do to fix this, lots of my users use Chunks Fade In, and it would be good if they dont have to uninstall either of our mods.

**Comment by IMB11** [comment] 2024-07-07 16:44
`Caused by: java.lang.NullPointerException: Cannot invoke "com.koteinik.chunksfadein.extensions.RenderSectionManagerExt.getAnimationOffset(int, int, int)" because "this.renderSectionManager" is null`

You need to add null checks.

**Comment by kerudion** [comment] 2024-07-07 17:50
Fixed in the new releases

**Closed by kerudion** 2024-07-07 17:50 UTC
Labels: bug
