### ISSUE TITLE
sodium compatibility

### ISSUE THREAD

**Issue by Palmboom76** [kerudion/chunksfadein#65] opened 2024-01-30 11:40 UTC
**What is the issue?**
seems to crash whenever joining a world

**Conditions to reproduce**
when on newer sodium versions joining a world or server closes mc

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
*Yes

**Full Minecraft logs**
https://mclo.gs/FuWswL9

**Comment by kerudion** [comment] 2024-01-31 07:07
Hello!
Looks like this issue is caused by the latest sodium update. So, I'll close this issue as a duplicate of https://github.com/kerudion/chunksfadein/issues/65, which I'll fix today

**Comment by kerudion** [comment] 2024-01-31 08:18
Hi!
I've fixed this issue for both 1.20.2+ ([1e5f7ff](https://github.com/kerudion/chunksfadein/commit/1e5f7ff6aac4796dd8b8a36dacf7c9e5c666846b)) and 1.20.1 ([63a71b0](https://github.com/kerudion/chunksfadein/commit/63a71b0242de46137995a076e36cbe071e38f884)) versions. I'll publish them soon

**Closed by kerudion** 2024-01-31 08:18 UTC
Labels: bug
