### ISSUE TITLE
Sinytra Connector Crash

### ISSUE THREAD

**Issue by MidasMischief** [kerudion/chunksfadein#66] opened 2024-01-30 21:45 UTC
**What is the issue?**
Hello! I've followed your instructions on getting the mod to run on forge via sinytra connector and the game launches, however when loading into a world the game crashes.

**Conditions to reproduce**
Install the latest version of embeddium, follow instructions on github page to run the mod in forge, load into a world.

**Does this issue appear only with Sodium, Iris and Chunks Fade In?**
No

**Full Minecraft logs**

[latest.log](https://github.com/kerudion/chunksfadein/files/14104683/latest.log)

**Comment by kerudion** [comment] 2024-01-31 07:07
Hello!
Looks like this issue is caused by the latest sodium update. So, I'll close this issue as a duplicate of https://github.com/kerudion/chunksfadein/issues/65, which I'll fix today

**Closed by kerudion** 2024-01-31 07:07 UTC
Labels: bug
